spring:
  application:

    name: auth-service

    jwt:
      secret: 
      access-expiration: 3600000
      token-expiration: 604800000

  datasource:
    url: jdbc:postgresql://auth_postgres:5432/auth_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: auth_redis
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: prgs2382@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG