server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index auth-frontend.html;
        try_files $uri $uri/ /auth-frontend.html;
    }
    location /api/ {
    proxy_pass http://auth-service:8081/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
}